CREATE DATABASE COLLEGE_DB;

USE COLLEGE_DB;

CREATE TABLE COLLEGE_STUDENTS(
		REG_ID INT,
		NAME VARCHAR(250),
        AGE INT,
        DEPT VARCHAR(3)
        );
                
ALTER TABLE COLLEGE_STUDENTS 
ADD EMAIL VARCHAR(100);

ALTER TABLE COLLEGE_STUDENTS
MODIFY COLUMN REG_ID VARCHAR(250);   

INSERT INTO COLLEGE_STUDENTS(REG_ID, NAME, AGE, DEPT)
VALUES  ('11','CHRIS','21','CSE'),
		('22','NOLAN','21','AI'),
        ('33','EVANS','22','ECE'),
        ('12','TONY','23','CSE'),
        ('44','OLSEN','20','EEE');

TRUNCATE TABLE COLLEGE_STUDENTS; 

INSERT INTO COLLEGE_STUDENTS(REG_ID, NAME, AGE, DEPT)
VALUES  ('11CS','CHRIS','21','CSE'),
		('22AI','NOLAN','21','AI'),
        ('33EC','EVANS','22','ECE'),
        ('12CS','TONY','23','CSE'),
        ('44EE','OLSEN','20','EEE');
        
 ALTER TABLE COLLEGE_STUDENTS
 DROP COLUMN EMAIL;
       
SELECT * FROM COLLEGE_STUDENTS;        
        
        
