CREATE DATABASE CUSTOMER_DB;

USE CUSTOMER_DB;

CREATE TABLE CUSTOMER_1(
		CUST_ID INT NOT NULL,
        CUST_NAME VARCHAR(250),
        CUST_LOCATION VARCHAR(100),
        CUST_PURCHASE INT,
        PRIMARY KEY(CUST_ID) 
        );
        
INSERT INTO CUSTOMER_1(CUST_ID, CUST_NAME, CUST_LOCATION, CUST_PURCHASE)
VALUES ('11', 'DHONI', 'CHENNAI','2500'),
		('22', 'JADEJA', 'CHENNAI','1500'),
        ('33', 'HARDIK', 'MUMBAI','5500'),
        ('44', 'ROHIT', 'MUMBAI','6500'),
        ('55', 'VIRAT', 'BANGALORE','3500'),
        ('66', 'SALT', 'BANGALORE','4500');
        			
UPDATE CUSTOMER_1
SET CUST_PURCHASE = '5500'
WHERE CUST_ID = 11;

DELETE FROM CUSTOMER_1
WHERE CUST_ID = 66;

SELECT * FROM CUSTOMER_1;






