CREATE DATABASE STUDENT;

USE STUDENT;

CREATE TABLE STUDENT(
		STUDENT_ID INT NOT NULL AUTO_INCREMENT,
        STUDENT_NAME VARCHAR(250),
        STUDENT_DOB DATETIME,
        PRIMARY KEY(STUDENT_ID)
        );
              
ALTER TABLE STUDENT
MODIFY COLUMN STUDENT_DOB DATE;

ALTER TABLE STUDENT
ADD STUDENT_YOJ YEAR;

INSERT INTO STUDENT(STUDENT_NAME, STUDENT_DOB, STUDENT_YOJ)
VALUES  ('VICKY', '2006-03-06', '2021'),
		('ZARA', '2003-06-03', '2019'),
        ('TATA', '2003-09-06', '2021'),
        ('ELON', '2006-06-09', '2019') ;
        
SELECT * FROM STUDENT;        
        

