CREATE DATABASE PERSON_DB;

USE PERSON_DB;

CREATE TABLE PERSON_1(
		ID INT NOT NULL,
        FIRST_NAME VARCHAR(250) NOT NULL,
        LAST_NAME VARCHAR(100),
        AGE INT
        );
        
ALTER TABLE PERSON_1
ADD CONSTRAINT PK_PERSON_1 PRIMARY KEY(ID, FIRST_NAME);

INSERT INTO PERSON_1(ID, FIRST_NAME, LAST_NAME, AGE)
VALUES
		('1', 'NICOLE','A','25'),
		('2', 'JENNIFER','W','26'),
		('3', 'EVA','L','27'),
		('4', 'TRU','K','26');
        
ALTER TABLE PERSON_1
DROP PRIMARY KEY;        
 
 SELECT * FROM PERSON_1;
 
 SELECT COUNT(AGE) FROM PERSON_1
 WHERE AGE > 25;
 
 SELECT SUM(AGE) FROM PERSON_1
 WHERE AGE >= 25;
 
 
		

      
