CREATE DATABASE PURCHASE_DB;

USE PURCHASE_DB;

CREATE TABLE PURCHASE_1(
		NAME VARCHAR(250),
        PURCHASE INT,
        COUNTRY VARCHAR(100),
        PRODUCT VARCHAR(250),
        AGE INT
        );
        
INSERT INTO PURCHASE_1(NAME, PURCHASE, COUNTRY, PRODUCT, AGE)
VALUES  ('TOM', '1000', 'AMERICA', 'BREAD', '20'),
		('MESSI', '1500', 'ARGENTINA', 'EGG', '21'),
        ('RONALDO', '2000', 'PORTUGAL', 'MILK', '22'),
        ('NOLAN', '2500', 'AMERICA', 'BREAD', '20'),
        ('VICKY', '1000', 'PORTUGAL', 'EGG', '22'),
        ('CHRIS', '1500', 'ARGENTINA', 'MILK', '22') ;
        
SELECT * FROM PURCHASE_1 
ORDER BY PURCHASE ASC;

SELECT COUNT(PRODUCT) AS TOTAL_PRODUCT
FROM PURCHASE_1 
GROUP BY PRODUCT;

SELECT COUNTRY, SUM(PURCHASE) AS TOTAL_PURCHASE
FROM PURCHASE_1
GROUP BY COUNTRY
ORDER BY TOTAL_PURCHASE;

SELECT MAX(AGE) AS MAX_AGE
FROM PURCHASE_1
GROUP BY AGE;

SELECT PRODUCT, SUM(PURCHASE) AS SUM_PURCHASE
FROM PURCHASE_1
GROUP BY PRODUCT
ORDER BY SUM_PURCHASE;

		