CREATE DATABASE STUDENT;

USE STUDENT;

CREATE TABLE STUDENT(
		ID INT NOT NULL,
		NAME VARCHAR(250),
        DEPT VARCHAR(5),
        AGE INT NOT NULL
        );
        
ALTER TABLE STUDENT 
ADD CONSTRAINT PK_STUDENT PRIMARY KEY(ID, AGE);        
        
INSERT INTO STUDENT(ID, NAME, DEPT, AGE)
VALUES  ('101', 'VIGNESH', 'CSE', '20'),
		('102', 'AJAY', 'CSE', '21'),
        ('201', 'TANIESH', 'AIDS', '20'),
        ('202', 'AAKIF', 'AIDS', '22'),
        ('301', 'ABUL', 'ECE', '21'),
        ('302', 'VIJAY', 'ECE', '20'),
        ('401', 'JOEL', 'IT', '21'),
        ('402', 'YASWAND', 'EEE', '22');
        
SELECT * FROM STUDENT 
WHERE AGE = 20 AND DEPT = 'CSE';

SELECT * FROM STUDENT 
WHERE AGE = 21 OR DEPT = 'AIML'; 

SELECT * FROM STUDENT 
WHERE NOT DEPT = 'ECE';

SELECT * FROM STUDENT 
WHERE AGE BETWEEN 21 AND 22
ORDER BY AGE;

SELECT DEPT, COUNT(AGE) AS TOTAL_COUNT
FROM STUDENT 
GROUP BY DEPT
ORDER BY TOTAL_COUNT;    