CREATE DATABASE TEST_DB;

USE TEST_DB;

CREATE TABLE EMPLOYEE(
		EMP_ID INT,
        EMP_AGE INT,
        EMP_NAME VARCHAR(250),
        EMP_PHONE INT
		);
        
SELECT EMP_ID, EMP_AGE, EMP_NAME FROM EMPLOYEE;        

CREATE TABLE EMPLOYEE2 AS
SELECT EMP_NAME, EMP_AGE 
FROM EMPLOYEE;

SELECT * FROM EMPLOYEE2;