CREATE DATABASE VIEW;

USE VIEW;

CREATE TABLE EMPLOYEE(
		EMP_ID INT NOT NULL AUTO_INCREMENT,
        EMP_NAME VARCHAR(200),
        EMP_AGE INT,
        EMP_SALARY INT,
        EMP_CITY VARCHAR(100),
        PRIMARY KEY(EMP_ID)
        );
        
INSERT INTO EMPLOYEE(EMP_NAME, EMP_AGE, EMP_SALARY, EMP_CITY)
VALUES  ('JOHN', '25', '45000', 'DELHI'),
		('JOCAB', '30', '55000', 'MUMBAI'),
        ('ALOK', '35', '65000', 'CHENNAI'),
        ('MENDES', '25', '35000', 'KERELA'),
        ('KEYNE', '20', '25000', 'DELHI'),
        ('LOIS', '25', '45000', 'CHENNAI') ;
        
CREATE VIEW EMP_DETAILS AS
SELECT  EMP_ID,
		EMP_NAME,
        EMP_AGE
FROM EMPLOYEE;

SELECT * FROM EMP_DETAILS;

DROP VIEW EMP_DETAILS;

CREATE OR REPLACE VIEW EMP_INFO AS
SELECT  EMP_NAME,
		EMP_AGE,
		EMP_SALARY,
        EMP_CITY
FROM EMPLOYEE;

SELECT * FROM EMP_INFO 
WHERE EMP_AGE BETWEEN 25 AND 35
ORDER BY EMP_AGE;

CREATE INDEX INDEX_INFO 
ON EMPLOYEE (EMP_ID, EMP_AGE);

CREATE UNIQUE INDEX INDEX_DETAILS
ON EMPLOYEE (EMP_NAME);

SELECT * FROM EMPLOYEE
WHERE EMP_AGE = '25';

ALTER TABLE EMPLOYEE
DROP INDEX INDEX_DETAILS;




        
		
		
        