SHOW DATABASES;

CREATE DATABASE STUDENT;

USE STUDENT;

CREATE TABLE STUDENT(
		ID INT NOT NULL AUTO_INCREMENT,
        NAME VARCHAR(100),
        AGE INT,
        PRIMARY KEY(ID)
        );
        
INSERT INTO STUDENT (NAME, AGE)
VALUES ('PAT', '20'),
	   ('HEAD', '21'),
       ('LYNN', '20'),	
       ('MARSH', '21'),	
       ('WATSON', '20'),	
       ('STARK', '21') ;

UPDATE STUDENT 
SET NAME = 'WARNER'
WHERE ID = '2';       

SELECT * FROM STUDENT;

CREATE TABLE EMPLOYEE(
		ID INT NOT NULL AUTO_INCREMENT,
        NAME VARCHAR(100),
        AGE INT,
        PRIMARY KEY(ID)
        );
        
INSERT INTO EMPLOYEE (NAME, AGE)
VALUES ('PAT', '20'),
	   ('HEAD', '21'),
       ('LYNN', '20'),	
       ('MARSH', '21'),	
       ('WATSON', '20'),	
       ('MAXWELL', '21') ;
       
SELECT * FROM EMPLOYEE;

SELECT S.NAME,
	   S.AGE,
       E.NAME,
       E.AGE
FROM STUDENT AS S
INNER JOIN EMPLOYEE AS E
ON S.NAME = E.NAME;

SELECT S.NAME,
	   S.AGE,
       E.NAME,
       E.AGE
FROM STUDENT AS S
LEFT JOIN EMPLOYEE AS E
ON S.NAME = E.NAME;

SELECT S.NAME,
	   S.AGE,
       E.NAME,
       E.AGE
FROM STUDENT AS S
RIGHT JOIN EMPLOYEE AS E
ON S.NAME = E.NAME;

SELECT S.NAME,
	   S.AGE,
       E.NAME,
       E.AGE
FROM STUDENT AS S
CROSS JOIN EMPLOYEE AS E
ON S.NAME = E.NAME;

TRUNCATE TABLE STUDENT;

ALTER TABLE STUDENT
ADD LOCATION VARCHAR(100);

INSERT INTO STUDENT (NAME, AGE, LOCATION)
VALUES ('PAT', '20', 'CHENNAI'),
	   ('HEAD', '21', 'DELHI'),
       ('LYNN', '20', 'KERELA'),	
       ('MARSH', '21', 'MUMBAI'),	
       ('WATSON', '20', 'CHENNAI'),	
       ('MAXWELL', '21', 'DELHI') ;
       
CREATE VIEW LOCATION_DETAILS 
AS SELECT NAME,
		  LOCATION
FROM STUDENT;

CREATE OR REPLACE VIEW UPDATED_DETAILS
AS SELECT ID,
		  NAME,
          AGE,
          LOCATION
FROM STUDENT;          

SELECT * FROM UPDATED_DETAILS
ORDER BY ID; 

SELECT AGE, COUNT(ID) AS AGE_DETAILS
FROM STUDENT
GROUP BY AGE;


      