CREATE DATABASE COLLEGE_DB;

USE COLLEGE_DB;

CREATE TABLE STUDENT1 (
		STUDENT_ID INT NOT NULL,
        STUDENT_NAME VARCHAR(100),
        STUDENT_DEPT VARCHAR(10),
        STUDENT_AGE INT NOT NULL,
        STUDENT_YOJ DATE
        );
        
ALTER TABLE STUDENT1
ADD CONSTRAINT PK_STUDENT1 PRIMARY KEY (STUDENT_ID, STUDENT_AGE);        

ALTER TABLE STUDENT1
MODIFY COLUMN STUDENT_YOJ YEAR;

CREATE TABLE FACULTY (
			FACULTY_ID INT NOT NULL AUTO_INCREMENT,
            FACULTY_NAME VARCHAR(100),
            STUDENT_DEPT VARCHAR(10),
            FACULTY_SALARY INT,
            PRIMARY KEY(FACULTY_ID)
            );
            
INSERT INTO STUDENT1 (STUDENT_ID, STUDENT_NAME, STUDENT_DEPT, STUDENT_AGE, STUDENT_YOJ)
VALUES  ('1', 'LOGAN', 'ÇSE', '21', '2023'),
        ('2', 'ROGUE', 'ÇSE', '20', '2024'),
        ('3', 'ERIC', 'ECE', '22', '2022'),
        ('4', 'RYAN', 'ECE', '23', '2021'),
        ('5', 'TONY', 'EEE', '21', '2023') ;
        
INSERT INTO FACULTY (FACULTY_NAME, STUDENT_DEPT, FACULTY_SALARY)
VALUES ('CHARLES', 'CSE', '45000'),
       ('JENE', 'ECE', '35000'),
       ('MAGNETO', 'EEE', '25000') ;
       
SELECT * FROM STUDENT1;

SELECT DISTINCT STUDENT_DEPT FROM STUDENT1; 

SELECT COUNT(DISTINCT STUDENT_ID) FROM STUDENT1;

UPDATE FACULTY
SET FACULTY_NAME = 'CHARLES XAVIER'
WHERE FACULTY_ID = 1;

DELETE FROM FACULTY 
WHERE FACULTY_NAME = 'CHARLES';

SELECT DISTINCT 
	   S.STUDENT_ID,
	   S.STUDENT_NAME,
       S.STUDENT_DEPT,
       F.FACULTY_NAME
FROM STUDENT1 AS S
INNER JOIN FACULTY AS F
ON S.STUDENT_DEPT = F.STUDENT_DEPT
ORDER BY STUDENT_ID;

CREATE VIEW DEPT_INFO AS
SELECT STUDENT_NAME,
	   STUDENT_DEPT,
       STUDENT_YOJ
FROM STUDENT1;

CREATE OR REPLACE VIEW NEW_INFO AS
SELECT	STUDENT_ID,
		STUDENT_NAME,
        STUDENT_DEPT
FROM STUDENT1;

SELECT * FROM NEW_INFO;




        
       
        
			
        


