CREATE TABLE STUDENT(
		STUDENT_ID INT NOT NULL AUTO_INCREMENT,
        STUDENT_NAME VARCHAR(100),
        STUDENT_DEPT VARCHAR(10),
        STUDENT_AGE INT,
        PRIMARY KEY(STUDENT_ID)
        );
        
INSERT INTO STUDENT(STUDENT_NAME, STUDENT_DEPT, STUDENT_AGE)
VALUES ('HAVOC', 'CSE', '20'),
	   ('RAVAN', 'CSE', '21'),
       ('ERIC', 'ECE', '20'),
       ('XAVIER', 'ECE', '21'),
       ('JENE', 'EEE', '20') ;

DELIMITER  //       
CREATE PROCEDURE GET_ALL_STUDENTS()
BEGIN
    SELECT *
    FROM STUDENT;
END//
DELIMITER ;

CALL GET_ALL_STUDENTS();

DELIMITER //
CREATE PROCEDURE STUDENT_INFO(
	IN	S_NAME VARCHAR(100),
    IN  S_AGE INT
    ) 
BEGIN
SELECT * FROM STUDENT
WHERE STUDENT_NAME = S_NAME
AND STUDENT_AGE = S_AGE;
END //
DELIMITER ;

CALL STUDENT_INFO('JENE', '20');     

   

        