CREATE TABLE ACCOUNTS (
		ACCOUNT_ID INT,
        ACCOUNT_NAME VARCHAR(100),
        ACCOUNT_BALANCE INT 
        );

INSERT INTO ACCOUNTS (ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_BALANCE)
VALUES ('101', 'LEO', '5000'),
       ('102', 'WOLF', '4000') ; 
       
START TRANSACTION;

UPDATE ACCOUNTS 
SET ACCOUNT_BALANCE = 3000 
WHERE ACCOUNT_ID = 101;

UPDATE ACCOUNTS 
SET ACCOUNT_BALANCE = '2500' 
WHERE ACCOUNT_ID = '102';

COMMIT;

BEGIN;
ALTER TABLE ACCOUNTS
ADD LOCATION VARCHAR(100);
COMMIT;

START TRANSACTION;
ALTER TABLE ACCOUNTS
DROP COLUMN LOCATION;
COMMIT;

BEGIN;
INSERT INTO ACCOUNTS VALUES ('103', 'BULL', '1000');
ROLLBACK;

SELECT * FROM ACCOUNTS;



        